In [2]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv("synthetic.csv")
cols = df.columns.values.tolist()

Attr_A
Attr_B
Attr_C
Attr_D
Attr_E
Attr_F
Attr_G
Attr_H
Attr_I
Attr_J
Attr_K
Attr_L
Attr_M
Attr_N

In [15]:
# df.sort_values(by=['Class']).tail(10)
ech = df.sample(100)
ech

,Attr_A,Attr_B,Attr_C,Attr_D,Attr_E,Attr_F,Attr_G,Attr_H,Attr_I,Attr_J,Attr_K,Attr_L,Attr_M,Attr_N,Class
992,11.455762,10.958984,940.597908,88.605428,130.927113,884.937847,9.597582,8.131245,13.495114,112.834274,899.282189,8.876852,978.666708,89.252260,2
239,13.122179,10.460414,996.028314,114.983115,91.103368,1103.731143,10.126066,11.781347,11.620376,95.809197,1069.568671,11.101074,961.058147,99.893009,1
2088,8.959012,11.290937,1099.665175,97.955974,118.433728,1104.300128,9.977233,9.623823,11.837119,83.713640,897.801646,9.707946,1066.625854,122.968281,2
1655,10.508696,10.683752,776.924931,94.472193,110.571166,798.801937,8.673173,10.865949,11.953684,118.902814,1199.616972,11.155949,1029.995647,110.803058,2
2138,10.184168,9.620717,859.114964,106.739444,91.842978,503.421855,8.637835,13.907218,7.997799,90.822446,1086.540327,9.490071,1048.698471,72.455939,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1613,10.005461,9.680270,950.320691,94.241598,118.991185,1159.627461,9.506624,9.253409,11.165066,92.503766,963.818601,9.017606,981.824419,83.207707,1
1712,9.829278,11.719817,794.605681,89.223810,104.986437,931.060419,9.915957,12.442897,9.035129,94.667627,958.478736,11.263418,1085.440678,123.809830,2
230,9.187521,8.215358,884.631452,94.058764,127.743671,944.840536,11.513541,13.805003,9.793009,78.932583,823.928069,10.569028,974.982337,85.094262,0
22,11.024802,9.796339,720.091322,97.537256,97.514606,993.866632,10.493588,9.975881,8.523809,76.126720,810.262267,8.551419,960.866959,100.112165,1
2142,11.985958,8.823458,662.106037,96.903112,98.699048,955.080797,9.357192,10.796803,10.211226,85.733663,1001.199607,10.597949,1122.254415,115.895632,1

In [ ]:
import seaborn as sns
sns.pairplot(ech , hue="Class")